### ISSUE TITLE
[Android] Getting these errors in Logcat (android studio) when running a project on android 

### ISSUE THREAD

**Issue by et-nat1995** [chaimPaneth/react-native-jw-media-player#101]
```
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.appgoalz.rnjwplayer.RNJWPlayerViewManager
W/System.err:     at com.longtailvideo.jwplayer.g.b.a(SourceFile:39)
W/System.err:     at com.longtailvideo.jwplayer.JWPlayerView.onAttachedToWindow(SourceFile:46083)
W/System.err:     at com.appgoalz.rnjwplayer.RNJWPlayerView.setupPlayerWithFirstItem(RNJWPlayerView.java:753)
W/System.err:     at com.appgoalz.rnjwplayer.RNJWPlayerView.setPlaylist(RNJWPlayerView.java:671)
W/System.err:     at com.appgoalz.rnjwplayer.RNJWPlayerViewManager.setPlaylist(RNJWPlayerViewManager.java:190)
```

The project I am working in was a managed expo workflow that i ejected to a bare workflow. For iOS i was able to get a working player, but having issues with android.
Followed the SDK installation with gradle as recommended from JWplayer.
Added the needed skd keys in the AndroidManifest.xml
Added the needed receiver block for the controls in the control center
Followed the set up as mentioned on README of this repo

added these dependencies in build.gradle (../android/app)
```
dependencies{
    implementation 'androidx.media:media:1.2.0'
    implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.18.2'
}
```

I am unable to get the player to work on Android i am assuming due to the error above. Any way to fix this error? Did I miss something? Do i still need to follow the steps for manual installation?

**Comment by chaimPaneth** [comment]
Hi @et-nat1995 

Did you install the latest version of this library via regular `npm install`?
Are you using android x?
You shouldn't have to define `implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.18.2'` in the `android/app/build.gradle` only the `implementation 'androidx.media:media:1.2.0'` line, this is needed only if you want background audio and you set the below in your AndroidManifest.xml
```
<receiver android:name="androidx.media.session.MediaButtonReceiver"> // this is why you need the media dependency in android/app
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
```

Try doing a clear cache for npm and for android it's always a good start...

Thank you.

**Comment by et-nat1995** [comment]
Hi @chaimPaneth 

Yes I installed the latest version of this library using yarn/npm. Version 0.1.52.
I am using android 10.0, release name Q, API level 29

Cleared yarn cache reinstalled the library.
Removed the definition for `implementation 'com.longtailvideo.jwplayer:jwplayer-core:3.18.2'`

Rebuilt and installed the app on a simulator, in logcat on verbose i am getting this error as well:
```
 E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Are there any working examples of a bare workflow, working video player for android?
Reason i am asking for a bare workflow, I am working in a test project before I eject a managed expo workflow. I built an app using expo and the requirements for the app is the use of jwPlayer. Not many other options out there for react native and jwplayer.

Any help on getting Android to work would be appreciated.

Thank you.

**Comment by chaimPaneth** [comment]
Hi @et-nat1995 the above error usually means your setting a prop on the player that isn't exported to the JS bridge can you show me an example of how you implement the player in your JS.

Check out https://stackoverflow.com/questions/42981703/react-native-could-not-find-generated-setter-for-class && https://github.com/facebook/react-native/issues/6692

The second link is about a google play services mismatch that might be the case here as well.

What is your `react-native` version?

**Comment by et-nat1995** [comment]
Hi @chaimPaneth 

Yup that was the issue. Wasn't sure how to read that error and what it meant. First time working on a bare workflow.
Thank you for answering my questions with prompt responses. Really appreciate it. 

Due to how the JWplayer account is set up its using an older api not the current v2/ as you mentioned in my other issue. I had to make a get request to that api and build the playlistItem object based on that return. Did all of this in a useEffect that set a state variable, iOS didn't have any issue with this but android wasn't happy.

Added a isLoading state and that worked.

Putting this out here incase others run into this issue:
```
import { StatusBar } from 'expo-status-bar';
import React, {useRef, useState, useEffect} from 'react';
import { StyleSheet, Text, View, SafeAreaView, ActivityIndicator } from 'react-native';
import JWPlayer from 'react-native-jw-media-player';

export default function App() {
  const [playlist, setPlalist] = useState([]);
  const [isLoading, setIsLoading] = useState(true)
  let jwPLayer = useRef();


  useEffect(() => {
    async function buildPlaylist() {
      let data = await fetch(`https://content.jwplatform.com/feeds/MEDIA_ID.json`);
      let res = await data.json();
      console.log(res.playlist);
      let newPlaylistArray = res.playlist.map(data => {
        let arrayOfSources = data.sources.filter(({label}) => label !== 'AAC Audio')
        return {
          title: data.title,
          mediaId: data.mediaid,
          desc: '',
          time: 0,
          file: arrayOfSources.slice(-1)[0].file,
          autostart: false,
          controls: true,
          repeat: false,
          displayDescription: false,
          displayTitle: false,
          backgroundAudioEnabled: true,
          image: data.images.slice(-1)[0].src
        }
      })
      setPlalist(newPlaylistArray);
      setIsLoading(false);
    }
    buildPlaylist();
  }, [])

  return (
    <>
      <StatusBar style="dark" />
      <SafeAreaView>
        <View style={styles.container}>
          {
            isLoading
              ? <ActivityIndicator size="small" color="#0000ff" />
              : <JWPlayer
                  ref={p => jwPLayer.current = p}
                  style={styles.player}
                  playlist={playlist} // Recommended - pass the playlistItem as a prop into the player
                  fullScreenOnLandscape={true}
                  landscapeOnFullScreen={true}
                  portraitOnExitFullScreen={true}
                  nativeFullScreen={true}
                />
          }
        </View>
      </SafeAreaView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    height: 250,
    width: '100%',
    backgroundColor: '#fff',
  },
  player: {
    flex: 1,
  },
});
