### ISSUE TITLE
IllegalArgumentException: Cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#162]
There is ongoing crash for the past year that has not been looked at...
It's from crashlytics report. And I don't know how to reproduce this.
This is comming from various devices.

```
Fatal Exception: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
       at android.view.ViewGroup.addView(ViewGroup.java:5081)
       at android.view.ViewGroup.addView(ViewGroup.java:5061)
       at com.appgoalz.rnjwplayer.RNJWPlayerView$2$2.run(RNJWPlayerView.java:520)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

This is ongoing for more than a year....

**Comment by bobbychan** [comment]
Same here
```Thread Name: 'main'
Back traces starts.
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:5082)
	at android.view.ViewGroup.addView(ViewGroup.java:5062)
	at com.appgoalz.rnjwplayer.RNJWPlayerView$fullscreenHandler$2.run(RNJWPlayerView.java:436)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Back traces ends.```

**Comment by jacksonsmith** [comment]
Same here.

Someone could identify the root cause ?

**Comment by chaimPaneth** [comment]
Closing due to inactivity.
