### ISSUE TITLE
Android demo not working

### ISSUE THREAD

**Issue by zikwall** [chaimPaneth/react-native-jw-media-player#20]
Hi.
When I run the example on the Android, I get the following error:

```
 Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 23.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.648 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:25034) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at handleError (/home/ppc/React/Native/react-native-jw-media-player/Example/node_modules/react-native/local-cli/cliEntry.js:35:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:25034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

He also complains about `sdk.dir=/path/to/AndroidSDK`. the latter is solved by adding a file local.properties:

```
sdk.dir=/path/to/AndroidSDK
```

**Comment by chaimPaneth** [comment]
@zikwall 

Iv'e updated the example and tested it, it's working now.

Thanks you.
