### ISSUE TITLE
[Android]android.app.ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by bobbychan** [chaimPaneth/react-native-jw-media-player#234]
version:0.2.23
```Process Name: 'com.xxx'
Thread Name: 'main'
Back traces starts.
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{61e71f7 u0 com.xxx/com.jwplayer.pub.api.background.MediaService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2001)
	at android.app.ActivityThread.access$2800(ActivityThread.java:276)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Back traces ends.```

**Comment by nateshmbhat** [comment]
Any update on this?

**Comment by nateshmbhat** [comment]
As of the last release version 'release/0.2.33' the issue is still happening
