### ISSUE TITLE
[Android]java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent 

### ISSUE THREAD

**Issue by bobbychan** [chaimPaneth/react-native-jw-media-player#235]
version:0.2.25
```
Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent com.appgoalz.rnjwplayer.RNJWPlayer.getParent()' on a null object reference
	at com.appgoalz.rnjwplayer.RNJWPlayerView$fullscreenHandler.onFullscreenRequested(RNJWPlayerView.java:391)
	at com.longtailvideo.jwplayer.e.b.b(SourceFile:45)
	at com.longtailvideo.jwplayer.e.b.$r8$lambda$tHXS0bmDa2r_1vZXI89tn48JhbU(Unknown Source:0)
	at com.longtailvideo.jwplayer.e.b$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8344)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
Back traces ends.
```

**Comment by tara-singh-danu** [comment]
Facing the same issue on version 0.2.35

**Comment by jacksonsmith** [comment]
Hello Master @chaimPaneth and @jasonlipo 

What if we put a try catch function inside this [onFullscreenRequested](https://github.com/chaimPaneth/react-native-jw-media-player/blob/06c3f02258ddc9a08e7eba190ef1fb6932af1eb4/android/src/main/java/com/appgoalz/rnjwplayer/RNJWPlayerView.java#L385C25-L385C25) 


?
