### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{be35771 u0 kiwi.theplatform.android/com.jwplayer.pub.api.background.MediaService}

### ISSUE THREAD

**Issue by mukeshInf** [chaimPaneth/react-native-jw-media-player#252]
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{be35771 u0 kiwi.theplatform.android/com.jwplayer.pub.api.background.MediaService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2242)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2213)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by mukeshInf** [comment]
Hi Any Update? still happening with the latest versions.

**Comment by jacksonsmith** [comment]
Still happens on the latest version.

react-native-jw-media-player [0.2.39]
react-native: "0.71.7


`Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{78d846e u0 br.com.sanarflix/com.jwplayer.pub.api.background.MediaService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by fdobre** [comment]
Having the same issue:

```
"react-native-jw-media-player": "0.2.37",
"react-native": "0.71.1",
```

Anybody knowing any workaround for this? This is my top 1 crash right now with thousands of crashes every week...
